const { generateAndSendReport } = require("./AutomatedReport");
const { scanCompetitor } = require("./GoogleAdsScanner");
const { pushScanToSheets, syncPublisherLinksToSheets } = require("./GoogleSheetsSync"); 
const EventEmitter = require('events');
const cron = require('node-cron');
const express = require("express");
const cors = require("cors");
const fs = require("fs"); 
const db = require("./database");

const addColumn = (table, column, type) => {
  try { db.prepare(`ALTER TABLE ${table} ADD COLUMN ${column} ${type}`).run(); } catch (e) {}
};

addColumn("games", "similar_apps", "TEXT");
addColumn("games", "installs", "TEXT");
addColumn("games", "min_installs", "INTEGER");
addColumn("games", "released", "TEXT");
addColumn("games", "updated", "INTEGER");
addColumn("games", "ad_count", "INTEGER DEFAULT 1");
addColumn("games", "icon", "TEXT");
addColumn("games", "screenshots", "TEXT");
addColumn("games", "description", "TEXT");
addColumn("games", "header_image", "TEXT");
addColumn("games", "video", "TEXT");
addColumn("games", "video_image", "TEXT");

try {
  db.prepare(`CREATE TABLE IF NOT EXISTS target_lists (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, targets TEXT NOT NULL, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP)`).run();
  db.prepare(`CREATE TABLE IF NOT EXISTS ad_history (id INTEGER PRIMARY KEY AUTOINCREMENT, game_id INTEGER NOT NULL, ad_count INTEGER NOT NULL, scan_date DATE DEFAULT CURRENT_DATE, UNIQUE(game_id, scan_date))`).run();
  db.prepare(`CREATE TABLE IF NOT EXISTS competitor_history (id INTEGER PRIMARY KEY AUTOINCREMENT, competitor_id INTEGER NOT NULL, total_ads INTEGER NOT NULL, scan_date DATE DEFAULT CURRENT_DATE, UNIQUE(competitor_id, scan_date))`).run();
  
  db.prepare(`CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT)`).run();
  const initSetting = (key, val) => { db.prepare(`INSERT OR IGNORE INTO settings (key, value) VALUES (?, ?)`).run(key, String(val)); };
  initSetting("ghost_scan_enabled", "1");
  initSetting("auto_report_enabled", "1");
  initSetting("default_report_email", "danish1042awan@gmail.com");
  initSetting("report_subject_template", "Atlas Daily Intelligence Briefing");
  initSetting("report_notes", "Automated competitive intelligence snapshot generated by Atlas node.");
  initSetting("google_sheet_id", "1tQysvSfuGZ3p9sydcueagW4fS_h2PufqDN0nx3i7ohs");
} catch (e) { console.error("Table Init Error:", e); }

const gplayRaw = require('google-play-scraper');
const scanEvents = new EventEmitter();
const gplay = gplayRaw.default || gplayRaw;

const app = express();
app.use(cors());
app.use(express.json());

// --- 🛑 GLOBAL KILL SWITCH STATE ---
let activeScanCancelled = false;

app.post("/api/cancel-scan", (req, res) => {
  activeScanCancelled = true;
  res.json({ status: "success", message: "Abort signal sent to active scan." });
});

app.get("/api/health", (req, res) => res.json({ status: "ok" }));

app.get("/api/stats", (req, res) => {
  const competitors = db.prepare("SELECT COUNT(*) AS count FROM competitors").get().count;
  const accounts = db.prepare("SELECT COUNT(*) AS count FROM accounts").get().count;
  const games = db.prepare("SELECT COUNT(*) AS count FROM games").get().count;
  res.json({ competitors, accounts, games });
});

app.get("/api/settings", (req, res) => {
  try {
    const rows = db.prepare("SELECT * FROM settings").all();
    const config = {};
    rows.forEach(r => { config[r.key] = r.value; });
    res.json(config);
  } catch (err) { res.status(500).json({ error: "Failed to fetch settings" }); }
});

app.post("/api/settings", (req, res) => {
  try {
    const updates = req.body;
    const stmt = db.prepare("INSERT OR REPLACE INTO settings (key, value) VALUES (?, ?)");
    const updateMany = db.transaction((cfg) => { for (const [k, v] of Object.entries(cfg)) { stmt.run(k, String(v)); } });
    updateMany(updates);
    res.json({ status: "success", settings: updates });
  } catch (err) { res.status(500).json({ error: "Failed to save settings" }); }
});

app.post("/api/reset", (req, res) => {
  try {
    db.prepare("DELETE FROM account_games").run();
    db.prepare("DELETE FROM games").run();
    db.prepare("DELETE FROM accounts").run();
    db.prepare("DELETE FROM ad_history").run();
    db.prepare("DELETE FROM competitor_history").run();
    db.prepare("DELETE FROM competitors WHERE ads_id IS NULL OR name = ads_id").run();
    res.json({ status: "success" });
  } catch (err) { res.status(500).json({ error: "Failed to reset" }); }
});

app.get("/api/trending", (req, res) => {
  try { res.json(db.prepare(`SELECT g.*, a.publisher_name, c.name AS competitor_name FROM games g LEFT JOIN account_games ag ON g.id = ag.game_id LEFT JOIN accounts a ON ag.account_id = a.id LEFT JOIN competitors c ON a.competitor_id = c.id ORDER BY g.ad_count DESC`).all()); } catch (err) { res.status(500).json({ error: "Fail" }); }
});

app.get("/api/competitor-history", (req, res) => {
  try { res.json(db.prepare(`SELECT ch.*, c.name FROM competitor_history ch JOIN competitors c ON ch.competitor_id = c.id ORDER BY ch.scan_date ASC`).all()); } catch (err) { res.status(500).json({ error: "Fail" }); }
});

app.post("/api/dev/seed-history", (req, res) => {
  try {
    const competitors = db.prepare("SELECT id FROM competitors").all();
    const stmt = db.prepare("INSERT OR REPLACE INTO competitor_history (competitor_id, total_ads, scan_date) VALUES (?, ?, date('now', ?))");
    competitors.forEach(c => {
      let baseAds = Math.floor(Math.random() * 25) + 10;
      for (let i = 0; i < 7; i++) {
        baseAds = Math.max(1, baseAds + (Math.floor(Math.random() * 7) - 3));
        stmt.run(c.id, baseAds, `-${6 - i} days`);
      }
    });
    res.json({ success: true });
  } catch (err) { res.status(500).json({ error: err.message }); }
});

try { db.prepare(`CREATE TABLE IF NOT EXISTS email_lists (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, emails TEXT NOT NULL)`).run(); } catch (e) { }

app.get("/api/emails", (req, res) => { try { res.json(db.prepare("SELECT * FROM email_lists ORDER BY id DESC").all()); } catch (err) { res.status(500).json({ error: "Fail" }); } });
app.post("/api/emails", (req, res) => { try { db.prepare("INSERT INTO email_lists (name, emails) VALUES (?, ?)").run(req.body.name, JSON.stringify(req.body.emails)); res.json({ status: "success" }); } catch (err) { res.status(500).json({ error: "Fail" }); } });
app.delete("/api/emails/:id", (req, res) => { try { db.prepare("DELETE FROM email_lists WHERE id = ?").run(req.params.id); res.json({ status: "success" }); } catch (err) { res.status(500).json({ error: "Fail" }); } });

app.get("/api/lists", (req, res) => { try { res.json(db.prepare("SELECT * FROM target_lists ORDER BY created_at DESC").all().map(list => ({ ...list, targets: JSON.parse(list.targets) }))); } catch (err) { res.status(500).json({ error: "Fail" }); } });
app.post("/api/lists", (req, res) => { try { const result = db.prepare("INSERT INTO target_lists (name, targets) VALUES (?, ?)").run(req.body.name, JSON.stringify(req.body.targets)); res.json({ id: result.lastInsertRowid, name: req.body.name, targets: req.body.targets, is_active: 1 }); } catch (err) { res.status(500).json({ error: "Fail" }); } });
app.patch("/api/lists/:id/toggle", (req, res) => { try { db.prepare("UPDATE target_lists SET is_active = ? WHERE id = ?").run(req.body.is_active ? 1 : 0, req.params.id); res.json({ status: "success" }); } catch (err) { res.status(500).json({ error: "Fail" }); } });
app.delete("/api/lists/:id", (req, res) => { try { db.prepare("DELETE FROM target_lists WHERE id = ?").run(req.params.id); res.json({ status: "success" }); } catch (err) { res.status(500).json({ error: "Fail" }); } });

try { db.prepare("ALTER TABLE competitors ADD COLUMN ads_id TEXT").run(); } catch (e) { }

app.get("/api/saved-competitors", (req, res) => { try { res.json(db.prepare("SELECT * FROM competitors WHERE ads_id IS NOT NULL AND name != ads_id ORDER BY id DESC").all()); } catch(err) { res.status(500).json({error: "Fail"}); } });
app.delete("/api/saved-competitors/:id", (req, res) => {
  try {
    db.prepare("SELECT id FROM accounts WHERE competitor_id = ?").all(req.params.id).forEach(acc => { db.prepare("DELETE FROM account_games WHERE account_id = ?").run(acc.id); });
    db.prepare("DELETE FROM accounts WHERE competitor_id = ?").run(req.params.id);
    db.prepare("DELETE FROM competitors WHERE id = ?").run(req.params.id);
    res.json({ status: "success" });
  } catch (err) { res.status(500).json({ error: "Fail" }); }
});

app.get("/api/scan-stream", (req, res) => {
  res.writeHead(200, { "Content-Type": "text/event-stream", "Cache-Control": "no-cache, no-transform", "Connection": "keep-alive" });
  res.write(`data: ${JSON.stringify({ log: "> Secure SSE connection established..." })}\n\n`);
  const sendProgress = (data) => { res.write(`data: ${JSON.stringify(data)}\n\n`); };
  scanEvents.on("progress", sendProgress);
  req.on("close", () => { scanEvents.off("progress", sendProgress); });
});

app.post("/api/scan", async (req, res) => {
  const { searchQuery, scanType, targetId, targetCountry, limit, sendReport, emailListId } = req.body;
  activeScanCancelled = false; // Reset the kill switch on new scan
  
  try {
    let targets = []; 
    if (scanType === "list") {
      const list = db.prepare("SELECT targets FROM target_lists WHERE id = ?").get(targetId);
      if (list) targets = JSON.parse(list.targets).map(t => ({ query: t, name: t, adsId: t.startsWith('AR') ? t : null }));
    } else if (scanType === "competitor") {
      const comp = db.prepare("SELECT name, ads_id FROM competitors WHERE id = ?").get(targetId);
      if (comp) targets = [{ query: comp.ads_id || comp.name, name: comp.name, adsId: comp.ads_id }];
    } else {
      targets = [{ query: searchQuery, name: searchQuery, adsId: searchQuery.startsWith('AR') ? searchQuery : null }];
    }

    if (targets.length === 0) return res.status(400).json({ error: "No targets specified" });

    const fixUrl = (url) => url && url.startsWith('//') ? 'https:' + url : url;
    let allResults = [];
    let isolatedScanData = []; 

    for (let tIndex = 0; tIndex < targets.length; tIndex++) {
      if (activeScanCancelled) break; // 🛑 CHECK KILL SWITCH
      
      const targetQuery = targets[tIndex].query;
      let targetAdsId = targets[tIndex].adsId;
      let targetDisplayName = targets[tIndex].name;

      let compQuery = null;
      if (targetAdsId) {
        compQuery = db.prepare(`SELECT id, name, ads_id FROM competitors WHERE ads_id = ? ORDER BY CASE WHEN name != ads_id THEN 0 ELSE 1 END, id DESC LIMIT 1`).get(targetAdsId);
      } else {
        compQuery = db.prepare("SELECT id, name, ads_id FROM competitors WHERE name = ? ORDER BY id DESC LIMIT 1").get(targetDisplayName);
      }

      if (compQuery && compQuery.name !== targetAdsId && compQuery.name !== compQuery.ads_id) { targetDisplayName = compQuery.name; } 
      else if (targetAdsId) { targetDisplayName = `Unsaved (${targetAdsId})`; }

      let competitorId;
      if (!compQuery) {
        const resComp = db.prepare("INSERT INTO competitors (name, ads_id, country) VALUES (?, ?, ?)").run(targetDisplayName, targetAdsId, targetCountry);
        competitorId = resComp.lastInsertRowid;
      } else {
        competitorId = compQuery.id;
        if (compQuery.name === targetAdsId && targetDisplayName !== targetAdsId) { db.prepare("UPDATE competitors SET name = ? WHERE id = ?").run(targetDisplayName, competitorId); }
      }

      // NOTE: We pass activeScanCancelled into the scanner conceptually, but breaking out of the packages loop handles it cleanly.
      const results = await scanCompetitor(targetQuery, targetCountry, limit, (progressData) => {
        scanEvents.emit("progress", { ...progressData, target: targetDisplayName, targetIndex: tIndex + 1, totalTargets: targets.length });
      });

      if (activeScanCancelled) break; // 🛑 CHECK KILL SWITCH

      const adCounts = {};
      results.forEach(pkg => { adCounts[pkg] = (adCounts[pkg] || 0) + 1; });
      const uniquePackages = [...new Set(results)];
      let totalCompetitorAds = 0;

      for (let i = 0; i < uniquePackages.length; i++) {
        if (activeScanCancelled) break; // 🛑 CHECK KILL SWITCH
        
        const pkg = uniquePackages[i];
        totalCompetitorAds += adCounts[pkg];
        scanEvents.emit("progress", { target: targetDisplayName, targetIndex: tIndex + 1, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> ⏳ Live Play Store parsing: ${pkg}... (${i+1}/${uniquePackages.length})` });

        try {
          const appData = await gplay.app({ appId: pkg, country: 'us' });
          const pubName = appData.developer || "Unknown Publisher";
          const normalizedPub = pubName.toLowerCase().replace(/[^a-z0-9]/g, "");
          
          let similarApps = [];
          try {
            const rawSimilar = await gplay.similar({ appId: pkg, country: 'us' });
            similarApps = (rawSimilar || []).filter(sim => sim.developer !== pubName).slice(0, 6).map(sim => ({ title: sim.title, appId: sim.appId, developer: sim.developer, icon: fixUrl(sim.icon), score: sim.score || 0 }));
          } catch (simErr) { }

          let accQuery = db.prepare("SELECT id FROM accounts WHERE publisher_name = ? AND competitor_id = ?").get(pubName, competitorId);
          let accountId;
          if (!accQuery) { accountId = db.prepare("INSERT INTO accounts (competitor_id, publisher_name, normalized_name) VALUES (?, ?, ?)").run(competitorId, pubName, normalizedPub).lastInsertRowid; } 
          else { accountId = accQuery.id; }

          const insertGame = db.prepare(`INSERT INTO games (package_name, title, category, rating, ratings_count, icon, screenshots, description, installs, min_installs, released, updated, similar_apps, ad_count, header_image, video, video_image) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(package_name) DO UPDATE SET title=excluded.title, category=excluded.category, rating=excluded.rating, ratings_count=excluded.ratings_count, icon=excluded.icon, screenshots=excluded.screenshots, description=excluded.description, installs=excluded.installs, min_installs=excluded.min_installs, released=excluded.released, updated=excluded.updated, similar_apps=excluded.similar_apps, ad_count=excluded.ad_count, header_image=excluded.header_image, video=excluded.video, video_image=excluded.video_image`);
          insertGame.run(pkg, appData.title, appData.genre, appData.score || 0, appData.ratings || 0, fixUrl(appData.icon), JSON.stringify((appData.screenshots || []).map(fixUrl)), appData.description, appData.installs || "0+", appData.minInstalls || 0, appData.released || "Unknown", appData.updated || 0, JSON.stringify(similarApps), adCounts[pkg], fixUrl(appData.headerImage) || null, appData.video || null, fixUrl(appData.videoImage) || null);
          
          const gameQuery = db.prepare("SELECT id FROM games WHERE package_name = ?").get(pkg);
          db.prepare("INSERT OR IGNORE INTO account_games (account_id, game_id) VALUES (?, ?)").run(accountId, gameQuery.id);

          try { db.prepare(`INSERT INTO ad_history (game_id, ad_count, scan_date) VALUES (?, ?, DATE('now')) ON CONFLICT(game_id, scan_date) DO UPDATE SET ad_count = excluded.ad_count`).run(gameQuery.id, adCounts[pkg]); } catch(err) { }
          isolatedScanData.push({ title: appData.title, publisher_name: pubName, category: appData.genre, rating: appData.score || 0, installs: appData.installs || "0+" });
          scanEvents.emit("progress", { target: targetDisplayName, targetIndex: tIndex + 1, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> 🎯 Saved: ${appData.title}` });
        } catch (err) { scanEvents.emit("progress", { target: targetDisplayName, targetIndex: tIndex + 1, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> ⚠️ Play Store fetch skipped for ${pkg}` }); }
      }
      
      if (activeScanCancelled) break; // 🛑 CHECK KILL SWITCH

      try { db.prepare(`INSERT INTO competitor_history (competitor_id, total_ads, scan_date) VALUES (?, ?, DATE('now')) ON CONFLICT(competitor_id, scan_date) DO UPDATE SET total_ads = excluded.total_ads`).run(competitorId, totalCompetitorAds); } catch(err) {}

      scanEvents.emit("progress", { target: targetDisplayName, targetIndex: tIndex + 1, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> 📊 Syncing data snapshot to Google Sheets...` });
      try { 
        await pushScanToSheets(db, targetDisplayName, results); 
        await syncPublisherLinksToSheets(db, targetDisplayName, targetAdsId);
      } catch (e) { console.error("Sheets Sync Error:", e); }
      
      allResults.push(...results);
    } 

    if (activeScanCancelled) {
      scanEvents.emit("progress", { target: "Scan Aborted", targetIndex: targets.length, totalTargets: targets.length, currentAd: 0, totalAds: limit, timeRemaining: "00:00", log: `> 🛑 Process cleanly terminated by user.` });
      return res.json({ status: "cancelled", data: allResults });
    }

    scanEvents.emit("progress", { target: "All Scans Complete", targetIndex: targets.length, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> 🎉 BATCH COMPLETE! Dashboard updating...` });

    if (sendReport === true && emailListId && emailListId !== "none" && isolatedScanData.length > 0) {
      scanEvents.emit("progress", { target: "Generating Report", targetIndex: targets.length, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> ✉️ Dispatching isolated PDF report email...` });
      try {
        const emailRow = db.prepare("SELECT emails FROM email_lists WHERE id = ?").get(emailListId);
        if (emailRow) {
          await generateAndSendReport(JSON.parse(emailRow.emails).join(", "), isolatedScanData);
          scanEvents.emit("progress", { target: "Generating Report", targetIndex: targets.length, totalTargets: targets.length, currentAd: limit, totalAds: limit, timeRemaining: "00:00", log: `> ✅ Email successfully dispatched!` });
        }
      } catch (err) { }
    }
    res.json({ status: "success", data: allResults });
  } catch (error) { res.status(500).json({ error: error.message }); }
});

app.post("/api/competitors", (req, res) => {
  const result = db.prepare("INSERT INTO competitors (name, ads_id, country) VALUES (?, ?, ?)").run(req.body.name, req.body.adsId || null, req.body.country || null);
  res.json({ id: result.lastInsertRowid, name: req.body.name, adsId: req.body.adsId || null });
});
app.post("/api/accounts", (req, res) => {
  const result = db.prepare("INSERT INTO accounts (competitor_id, publisher_name, normalized_name) VALUES (?, ?, ?)").run(req.body.competitorId || null, req.body.publisherName, req.body.publisherName.toLowerCase().replace(/[^a-z0-9]/g, ""));
  res.json({ id: result.lastInsertRowid });
});
app.post("/api/games", (req, res) => { res.json({status: "ok"}); });

app.get("/api/competitors", (req, res) => {
  const competitors = db.prepare("SELECT * FROM competitors").all();
  res.json(competitors.map((comp) => {
    return { ...comp, accounts: db.prepare("SELECT * FROM accounts WHERE competitor_id = ?").all(comp.id).map((acc) => {
      return { ...acc, games: db.prepare(`SELECT g.* FROM games g JOIN account_games ag ON g.id = ag.game_id WHERE ag.account_id = ?`).all(acc.id) };
    }) };
  }));
});

const PORT = 3000;

cron.schedule('0 3 * * *', async () => {
  const isEnabled = db.prepare("SELECT value FROM settings WHERE key = 'ghost_scan_enabled'").get()?.value;
  if (isEnabled !== "1") return;
  console.log("\n👻 [GHOST AUTOMATION] Running 3:00 AM background scans...");
  try {
    const targets = db.prepare("SELECT name, country FROM competitors").all();
    for (const target of targets) {
      await scanCompetitor(target.name, target.country || "Any", 500, () => {});
      await new Promise(resolve => setTimeout(resolve, 30000));
    }
  } catch (error) { console.error("👻 [GHOST AUTOMATION] Error:", error); }
});

cron.schedule('0 6 * * *', async () => {
  const isEnabled = db.prepare("SELECT value FROM settings WHERE key = 'auto_report_enabled'").get()?.value;
  if (isEnabled !== "1") return;
  const defaultEmail = db.prepare("SELECT value FROM settings WHERE key = 'default_report_email'").get()?.value || "danish1042awan@gmail.com";
  console.log(`\n⏰ [CRON] Triggering 6:00 AM Automated PDF Report to: ${defaultEmail}`);
  await generateAndSendReport(defaultEmail);
});

app.listen(PORT, () => console.log(`Atlas backend running on http://localhost:${PORT}`));